<?php
/**
 * PaymentsResponse
 *
 * PHP version 5
 *
 * @category Class
 * @package  Khipu
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2015 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

<?php

namespace Khipu\Model;

use ArrayAccess;

class PaymentsResponse implements ArrayAccess
{
    protected ?string $payment_id = null;
    protected ?string $payment_url = null;
    protected ?string $simplified_transfer_url = null;
    protected ?string $transfer_url = null;
    protected ?string $webpay_url = null;
    protected ?string $hites_url = null;
    protected ?string $payme_url = null;
    protected ?string $app_url = null;
    protected ?bool $ready_for_terminal = null;
    protected ?string $notification_token = null;
    protected ?int $receiver_id = null;
    protected ?\DateTime $conciliation_date = null;
    protected ?string $subject = null;
    protected ?float $amount = null;
    protected ?string $currency = null;
    protected ?string $status = null;
    protected ?string $status_detail = null;
    protected ?string $body = null;
    protected ?string $picture_url = null;
    protected ?string $receipt_url = null;
    protected ?string $return_url = null;
    protected ?string $cancel_url = null;
    protected ?string $notify_url = null;
    protected ?string $notify_api_version = null;
    protected ?\DateTime $expires_date = null;
    protected ?array $attachment_urls = null;
    protected ?string $bank = null;
    protected ?string $bank_id = null;
    protected ?string $payer_name = null;
    protected ?string $payer_email = null;
    protected ?string $personal_identifier = null;
    protected ?string $bank_account_number = null;
    protected ?bool $out_of_date_conciliation = null;
    protected ?string $transaction_id = null;
    protected ?string $custom = null;
    protected ?string $responsible_user_email = null;
    protected ?bool $send_reminders = null;
    protected ?bool $send_email = null;
    protected ?string $payment_method = null;
    protected ?string $funds_source = null;

    public function __construct(array $data = [])
    {
        foreach ($data as $key => $value) {
            if (property_exists($this, $key)) {
                $this->$key = $value;
            }
        }
    }

    // --- Getters y setters tipados ---
    public function getPaymentId(): ?string { return $this->payment_id; }
    public function setPaymentId(?string $payment_id): self { $this->payment_id = $payment_id; return $this; }

    public function getPaymentUrl(): ?string { return $this->payment_url; }
    public function setPaymentUrl(?string $payment_url): self { $this->payment_url = $payment_url; return $this; }

    public function getSimplifiedTransferUrl(): ?string { return $this->simplified_transfer_url; }
    public function setSimplifiedTransferUrl(?string $url): self { $this->simplified_transfer_url = $url; return $this; }

    public function getTransferUrl(): ?string { return $this->transfer_url; }
    public function setTransferUrl(?string $url): self { $this->transfer_url = $url; return $this; }

    public function getWebpayUrl(): ?string { return $this->webpay_url; }
    public function setWebpayUrl(?string $url): self { $this->webpay_url = $url; return $this; }

    public function getHitesUrl(): ?string { return $this->hites_url; }
    public function setHitesUrl(?string $url): self { $this->hites_url = $url; return $this; }

    public function getPaymeUrl(): ?string { return $this->payme_url; }
    public function setPaymeUrl(?string $url): self { $this->payme_url = $url; return $this; }

    public function getAppUrl(): ?string { return $this->app_url; }
    public function setAppUrl(?string $url): self { $this->app_url = $url; return $this; }

    public function getReadyForTerminal(): ?bool { return $this->ready_for_terminal; }
    public function setReadyForTerminal(?bool $val): self { $this->ready_for_terminal = $val; return $this; }

    public function getNotificationToken(): ?string { return $this->notification_token; }
    public function setNotificationToken(?string $token): self { $this->notification_token = $token; return $this; }

    public function getReceiverId(): ?int { return $this->receiver_id; }
    public function setReceiverId(?int $id): self { $this->receiver_id = $id; return $this; }

    public function getConciliationDate(): ?\DateTime { return $this->conciliation_date; }
    public function setConciliationDate(?\DateTime $dt): self { $this->conciliation_date = $dt; return $this; }

    public function getSubject(): ?string { return $this->subject; }
    public function setSubject(?string $subject): self { $this->subject = $subject; return $this; }

    public function getAmount(): ?float { return $this->amount; }
    public function setAmount(?float $amount): self { $this->amount = $amount; return $this; }

    public function getCurrency(): ?string { return $this->currency; }
    public function setCurrency(?string $currency): self { $this->currency = $currency; return $this; }

    public function getStatus(): ?string { return $this->status; }
    public function setStatus(?string $status): self { $this->status = $status; return $this; }

    public function getStatusDetail(): ?string { return $this->status_detail; }
    public function setStatusDetail(?string $detail): self { $this->status_detail = $detail; return $this; }

    public function getBody(): ?string { return $this->body; }
    public function setBody(?string $body): self { $this->body = $body; return $this; }

    public function getPictureUrl(): ?string { return $this->picture_url; }
    public function setPictureUrl(?string $url): self { $this->picture_url = $url; return $this; }

    public function getReceiptUrl(): ?string { return $this->receipt_url; }
    public function setReceiptUrl(?string $url): self { $this->receipt_url = $url; return $this; }

    public function getReturnUrl(): ?string { return $this->return_url; }
    public function setReturnUrl(?string $url): self { $this->return_url = $url; return $this; }

    public function getCancelUrl(): ?string { return $this->cancel_url; }
    public function setCancelUrl(?string $url): self { $this->cancel_url = $url; return $this; }

    public function getNotifyUrl(): ?string { return $this->notify_url; }
    public function setNotifyUrl(?string $url): self { $this->notify_url = $url; return $this; }

    public function getNotifyApiVersion(): ?string { return $this->notify_api_version; }
    public function setNotifyApiVersion(?string $v): self { $this->notify_api_version = $v; return $this; }

    public function getExpiresDate(): ?\DateTime { return $this->expires_date; }
    public function setExpiresDate(?\DateTime $dt): self { $this->expires_date = $dt; return $this; }

    public function getAttachmentUrls(): ?array { return $this->attachment_urls; }
    public function setAttachmentUrls(?array $urls): self { $this->attachment_urls = $urls; return $this; }

    public function getBank(): ?string { return $this->bank; }
    public function setBank(?string $bank): self { $this->bank = $bank; return $this; }

    public function getBankId(): ?string { return $this->bank_id; }
    public function setBankId(?string $id): self { $this->bank_id = $id; return $this; }

    public function getPayerName(): ?string { return $this->payer_name; }
    public function setPayerName(?string $name): self { $this->payer_name = $name; return $this; }

    public function getPayerEmail(): ?string { return $this->payer_email; }
    public function setPayerEmail(?string $mail): self { $this->payer_email = $mail; return $this; }

    public function getPersonalIdentifier(): ?string { return $this->personal_identifier; }
    public function setPersonalIdentifier(?string $id): self { $this->personal_identifier = $id; return $this; }

    public function getBankAccountNumber(): ?string { return $this->bank_account_number; }
    public function setBankAccountNumber(?string $n): self { $this->bank_account_number = $n; return $this; }

    public function getOutOfDateConciliation(): ?bool { return $this->out_of_date_conciliation; }
    public function setOutOfDateConciliation(?bool $v): self { $this->out_of_date_conciliation = $v; return $this; }

    public function getTransactionId(): ?string { return $this->transaction_id; }
    public function setTransactionId(?string $id): self { $this->transaction_id = $id; return $this; }

    public function getCustom(): ?string { return $this->custom; }
    public function setCustom(?string $custom): self { $this->custom = $custom; return $this; }

    public function getResponsibleUserEmail(): ?string { return $this->responsible_user_email; }
    public function setResponsibleUserEmail(?string $mail): self { $this->responsible_user_email = $mail; return $this; }

    public function getSendReminders(): ?bool { return $this->send_reminders; }
    public function setSendReminders(?bool $val): self { $this->send_reminders = $val; return $this; }

    public function getSendEmail(): ?bool { return $this->send_email; }
    public function setSendEmail(?bool $val): self { $this->send_email = $val; return $this; }

    public function getPaymentMethod(): ?string { return $this->payment_method; }
    public function setPaymentMethod(?string $method): self { $this->payment_method = $method; return $this; }

    public function getFundsSource(): ?string { return $this->funds_source; }
    public function setFundsSource(?string $source): self { $this->funds_source = $source; return $this; }

    // --- Métodos de ArrayAccess para PHP 8.1+ ---
    public function offsetExists(mixed $offset): bool
    {
        return property_exists($this, $offset);
    }

    public function offsetGet(mixed $offset): mixed
    {
        return $this->$offset ?? null;
    }

    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (property_exists($this, $offset)) {
            $this->$offset = $value;
        }
    }

    public function offsetUnset(mixed $offset): void
    {
        if (property_exists($this, $offset)) {
            $this->$offset = null;
        }
    }

    public function __toString(): string
    {
        return json_encode(get_object_vars($this), JSON_PRETTY_PRINT);
    }
}
